version: '3.8'

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Asuncion
    ports:
      - '9696:9696'
    volumes:
      - prowlarr_config:/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Asuncion
    ports:
      - '7878:7878'
    volumes:
      - radarr_config:/config
      - /mnt/win_media:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Asuncion
    ports:
      - '8989:8989'
    volumes:
      - sonarr_config:/config
      - /mnt/win_media:/media
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Asuncion
    ports:
      - '8191:8191'
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Asuncion
    ports:
      - '5055:5055'
    volumes:
      - jellyseerr_config:/app/config
    restart: unless-stopped

volumes:
  prowlarr_config:
  radarr_config:
  sonarr_config:
  jellyseerr_config:
